server:
  # debug release test
  model: release
  port: 8888
  cors: true
  tls:
    enable: false
    key-file: ./default.key
    cert-file: ./default.pem
  # 机器终端操作回放文件存储路径
  machine-rec-path: ./rec
jwt:
  # jwt key，不设置默认使用随机字符串
  key: 
  # 过期时间单位分钟
  expire-time: 1440
# 资源密码aes加密key
aes:
  key: 1111111111111111
mysql:
  host: 127.0.0.1
  username: root
  password: 123456
  db-name: magic
  config: charset=utf8mb4&loc=Local&parseTime=true
  max-idle-conns: 5
redis:
  host: 127.0.0.1
  password:
  port: 6379
  dbNum: 10
  poolSize: 10000
defaultLoad:
  mysql: true #是否默认启动mysql
  redis: true #是否默认启动redis
log:
   # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  # file:
  #   path: ./
  #   name: magic.log